# Generated by Django 5.0.2 on 2024-08-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_created_at_user_refresh_token_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
