# Generated by Django 5.0.2 on 2024-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_refresh_token_user_refresh_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(blank=True, max_length=50, null=True)),
                ('brandDescription', models.TextField()),
                ('brandUrl', models.URLField()),
            ],
        ),
    ]
