# Generated by Django 5.0.2 on 2024-09-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportCarName', models.CharField(blank=True, max_length=50, null=True)),
                ('sportsCarDescription', models.TextField()),
                ('sportsCarUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suvCarBrand', models.CharField(blank=True, max_length=50, null=True)),
                ('suvCarDescription', models.TextField()),
                ('suvCarUrl', models.URLField()),
            ],
        ),
    ]
