# Generated by Django 5.0.2 on 2024-09-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_carmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='modelDescrption',
            new_name='modelDescription',
        ),
    ]
